
/* !GENERATED FILE - DO NOT HAND EDIT! */

#pragma once

#define MONSTER_GOBLIN                  0
#define MONSTER_GOBLIN_GUARD            1
#define MONSTER_WOLF                    2
#define MONSTER_WARG_WOLF               3
#define MONSTER_WEREWOLF                4
#define MONSTER_WINTER_WOLF             5
#define MONSTER_LIZARD                  6
#define MONSTER_FIRE_LIZARD             7
#define MONSTER_BASILISK                8
#define MONSTER_HILL_GIGAS              9
#define MONSTER_ICE_GIGAS               10
#define MONSTER_FIRE_GIGAS              11
#define MONSTER_SAHAGIN                 12
#define MONSTER_SAHAGIN_CHIEF           13
#define MONSTER_SAHAGIN_PRINCE          14
#define MONSTER_PIRATE                  15
#define MONSTER_BUCCANEER               16
#define MONSTER_SHARK                   17
#define MONSTER_WHITE_SHARK             18
#define MONSTER_BIGEYES                 19
#define MONSTER_DEEPEYES                20
#define MONSTER_SKELETON                21
#define MONSTER_BLOODBONES              22
#define MONSTER_GIGAS_WORM              23
#define MONSTER_CRAWLER                 24
#define MONSTER_HYENADON                25
#define MONSTER_HELLHOUND               26
#define MONSTER_OGRE                    27
#define MONSTER_OGRE_CHIEF              28
#define MONSTER_OGRE_MAGE               29
#define MONSTER_COBRA                   30
#define MONSTER_ANACONDA                31
#define MONSTER_SEA_SNAKE               32
#define MONSTER_SCORPION                33
#define MONSTER_SEA_SCORPION            34
#define MONSTER_MINOTAUR                35
#define MONSTER_NECROTAUR               36
#define MONSTER_TROLL                   37
#define MONSTER_SEA_TROLL               38
#define MONSTER_SHADOW                  39
#define MONSTER_WRAITH                  40
#define MONSTER_SPECTER                 41
#define MONSTER_GHOST                   42
#define MONSTER_ZOMBIE                  43
#define MONSTER_GHOUL                   44
#define MONSTER_GHAST                   45
#define MONSTER_WIGHT                   46
#define MONSTER_PURPLE_WORM             47
#define MONSTER_SAND_WORM               48
#define MONSTER_LAVA_WORM               49
#define MONSTER_EVIL_EYE                50
#define MONSTER_DEATH_EYE               51
#define MONSTER_MEDUSA                  52
#define MONSTER_EARTH_MEDUSA            53
#define MONSTER_WERETIGER               54
#define MONSTER_RAKSHASA                55
#define MONSTER_CENTIPEDE               56
#define MONSTER_REMORA                  57
#define MONSTER_LESSER_TIGER            58
#define MONSTER_SABERTOOTH              59
#define MONSTER_VAMPIRE                 60
#define MONSTER_VAMPIRE_LORD            61
#define MONSTER_GARGOYLE                62
#define MONSTER_HORNED_DEVIL            63
#define MONSTER_EARTH_ELEMENTAL         64
#define MONSTER_FIRE_ELEMENTAL          65
#define MONSTER_WHITE_DRAGON            66
#define MONSTER_RED_DRAGON              67
#define MONSTER_DRAGON_ZOMBIE           68
#define MONSTER_GREEN_SLIME             69
#define MONSTER_GRAY_OOZE               70
#define MONSTER_OCHRE_JELLY             71
#define MONSTER_DARK_FLAN               72
#define MONSTER_BLACK_WIDOW             73
#define MONSTER_TARANTULA               74
#define MONSTER_MANTICORE               75
#define MONSTER_SPHINX                  76
#define MONSTER_BARETTA                 77
#define MONSTER_DESERT_BARETTA          78
#define MONSTER_MUMMY                   79
#define MONSTER_KING_MUMMY              80
#define MONSTER_COCKATRICE              81
#define MONSTER_PYROLISK                82
#define MONSTER_WYVERN                  83
#define MONSTER_WYRM                    84
#define MONSTER_ALLOSAURUS              85
#define MONSTER_TYRANNOSAUR             86
#define MONSTER_PIRANHA                 87
#define MONSTER_RED_PIRANHA             88
#define MONSTER_CROCODILE               89
#define MONSTER_WHITE_CROC              90
#define MONSTER_OCHU                    91
#define MONSTER_NEOCHU                  92
#define MONSTER_HYDRA                   93
#define MONSTER_FIRE_HYDRA              94
#define MONSTER_GUARDIAN                95
#define MONSTER_SOLDIER                 96
#define MONSTER_WATER_ELEMENTAL         97
#define MONSTER_AIR_ELEMENTAL           98
#define MONSTER_WATER_NAGA              99
#define MONSTER_SPIRIT_NAGA             100
#define MONSTER_CHIMERA                 101
#define MONSTER_RHYOS                   102
#define MONSTER_PISCODEMON              103
#define MONSTER_MINDFLAYER              104
#define MONSTER_GARLAND                 105
#define MONSTER_GREEN_DRAGON            106
#define MONSTER_BLUE_DRAGON             107
#define MONSTER_CLAY_GOLEM              108
#define MONSTER_STONE_GOLEM             109
#define MONSTER_IRON_GOLEM              110
#define MONSTER_BLACK_KNIGHT            111
#define MONSTER_DEATH_KNIGHT            112
#define MONSTER_ASTOS                   113
#define MONSTER_DARK_WIZARD             114
#define MONSTER_DARK_FIGHTER            115
#define MONSTER_CRAZY_HORSE             116
#define MONSTER_NIGHTMARE               117
#define MONSTER_WARMECH                 118
#define MONSTER_LICH                    119
#define MONSTER_LICH                    120
#define MONSTER_MARILITH                121
#define MONSTER_MARILITH                122
#define MONSTER_KRAKEN                  123
#define MONSTER_KRAKEN                  124
#define MONSTER_TIAMAT                  125
#define MONSTER_TIAMAT                  126
#define MONSTER_CHAOS                   127

