
/* !GENERATED FILE - DO NOT HAND EDIT! */

#pragma once

#define ARMOR_AEGIS_SHIELD              0
#define ARMOR_BUCKLER                   1
#define ARMOR_CRYSTAL_SHIELD            2
#define ARMOR_DIAMOND_SHIELD            3
#define ARMOR_ELVEN_CLOAK               4
#define ARMOR_FLAME_SHIELD              5
#define ARMOR_GENJI_SHIELD              6
#define ARMOR_HEROS_SHIELD              7
#define ARMOR_SHIELD                    8
#define ARMOR_IRON_SHIELD               9
#define ARMOR_LEATHER_SHIELD            10
#define ARMOR_MYTHRIL_SHIELD            11
#define ARMOR_PROTECT_CLOAK             12
#define ARMOR_ZEPHYR_CAPE               13
#define ARMOR_BLACK_COWL                14
#define ARMOR_CRYSTAL_HELM              15
#define ARMOR_DIAMOND_HELM              16
#define ARMOR_FEATHERED_CAP             17
#define ARMOR_GENJI_HELM                18
#define ARMOR_GREAT_HELM                19
#define ARMOR_HEALING_HELM              20
#define ARMOR_HELM                      21
#define ARMOR_LEATHER_CAP               22
#define ARMOR_MYTHRIL_HELM              23
#define ARMOR_                          24
#define ARMOR_RIBBON                    25
#define ARMOR_SAGES_MITRE               26
#define ARMOR_TWIST_HEADBAND            27
#define ARMOR_WIZARDS_HAT               28
#define ARMOR_BARDS_TUNIC               29
#define ARMOR_BLACK_GARB                30
#define ARMOR_BLACK_ROBE                31
#define ARMOR_CHAIN_MAIL                32
#define ARMOR_CLOTHES                   33
#define ARMOR_COPPER_ARMLET             34
#define ARMOR_CRYSTAL_MAIL              35
#define ARMOR_DIAMOND_ARMLET            36
#define ARMOR_DIAMOND_ARMOR             37
#define ARMOR_DRAGON_MAIL               38
#define ARMOR_FLAME_MAIL                39
#define ARMOR_GAIA_GEAR                 40
#define ARMOR_GENJI_ARMOR               41
#define ARMOR_ARMOR                     42
#define ARMOR_IRON_ARMOR                43
#define ARMOR_KENPOGI                   44
#define ARMOR_KNIGHTS_ARMOR             45
#define ARMOR_LEATHER_ARMOR             46
#define ARMOR_LIGHT_ROBE                47
#define ARMOR_MYTHRIL_MAIL              48
#define ARMOR_JACKET                    49
#define ARMOR_RUBY_ARMLET               50
#define ARMOR_SAGES_SURPLICE            51
#define ARMOR_SILVER_ARMLET             52
#define ARMOR_THIEFS_ARMLET             53
#define ARMOR_WHITE_ROBE                54
#define ARMOR_ANGELS_RING               55
#define ARMOR_BRONZE_GLOVES             56
#define ARMOR_CRYSTAL_GLOVES            57
#define ARMOR_DIAMOND_GLOVES            58
#define ARMOR_GENJI_GLOVES              59
#define ARMOR_GIANTS_GLOVES             60
#define ARMOR_LEATHER_GLOVES            61
#define ARMOR_MYTHRIL_GLOVES            62
#define ARMOR_PROTECT_RING              63
#define ARMOR_STEEL_GLOVES              64
#define ARMOR_THIEFS_GLOVES             65

