
#pragma once

// These types of things should probably be auto-generated by the editor
// for use by scripts.


enum ELEMENT_ENUM
{
	FIRE,
	ICE,
	LIT,
	EARTH,
	WIND,
	WATER,
	HOLY,
	DARK
};


/*
#define FIRE			0x0001
#define ICE				0x0002
#define LIT				0x0004
#define EARTH			0x0008
#define WIND			0x0010
#define WATER			0x0020
#define HOLY			0x0040
#define DARK			0x0080
#define ELEMENT_ALL		0x00ff
*/

