
#pragma once

// These types of things should probably be auto-generated by the editor
// for use by scripts.


//these might not be 100% right.
enum STATUS_EFFECT_ENUM
{
	DEATH,
	STONE,
	POISON,
	BLIND,
	PARALYZE,
	SLEEP,
	SILENCE,
	CONFUSE,
	PETRIFY
};


// look-up by bit-flags can be done but not as convienient as id.
// best to let the c++ code handle it. (At least we should have functions that do all the dirty work)
/*
#define DEATH		0x0001
#define STONE		0x0002
#define POISON		0x0004
#define BLIND		0x0008
#define PARALYZE	0x0010
#define SLEEP		0x0020
#define SILENCE		0x0040
#define CONFUSE		0x0080
//#define PETRIFY		0x0100
#define STATUS_ALL	0x00ff
*/



